Migrate from yarn to npm
d-zero-dev/linters pull request #160
Opened 2024-07-30 05:04 UTC by arktds

`yarn upgrade-interactive --latest` の代替として、npx で [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) の使用を想定しています。
その他の詳細はコミットメッセージに記載しています。

2024-07-30 12:09 UTC, YusukeHirao requested changes

2024-07-30 12:09 UTC, YusukeHirao commented on package.json
> +		"co": "cz"
```suggestion
		"co": "cz",
		"up": "npx npm-check-updates"
```

`up`コマンド自体は活用したいです。

2024-07-30 12:12 UTC, YusukeHirao commented
package.jsonに

```json
"packageManager": "npm@10.8.2",
```

を追加すると、`yarn`コマンドを実行した時にエラーが出て`npm`を使用しないといけないことに気づけて便利です。
（`corepack`をインストールしなくてもちゃんとエラーが出たので、環境に依存せずに振る舞ってくれました）

2024-08-13 08:50 UTC, arktds commented on package.json
> +		"co": "cz"
追加で次の2つのオプションを指定します。
- `--interactive`：`yarn upgrade-interactive` のようなインタラクティブモードで実行
- `--format group`：Patch/Minor/Major のグループ分け

```
npx npm-check-updates --interactive --format group
```

https://github.com/raineorshine/npm-check-updates?tab=readme-ov-file#interactive-mode

2024-08-13 09:34 UTC, arktds commented
Windows で textlint の対象から CHANGELOG.md の無視ができていないようで、テストが失敗してしまいます🤔

2024-09-02 04:31 UTC, YusukeHirao approved these changes

2024-09-02 04:31 UTC, merged