test(lint-staged): windowsでも、特定のファイルに対して特定のリンターの実行が除外できるように修正
d-zero-dev/linters pull request #176
Opened 2024-08-28 16:29 UTC by arktds

2024-09-02 04:30 UTC, YusukeHirao requested changes

2024-09-02 04:30 UTC, YusukeHirao commented on packages/@d-zero/lint-staged-config/src/index.ts
> +						console.log({ targetFiles, absIgnorePatterns });
```suggestion
```

2024-09-02 04:30 UTC, YusukeHirao commented on packages/@d-zero/lint-staged-config/src/index.ts
> +						console.log({ targetFiles, absIgnorePatterns });
console.logの削除お願いします

2024-09-24 14:32 UTC, arktds commented
@YusukeHirao 
GitHub Actions のテスト結果を確認するため WIP としてドラフトプルリクエストにしていましたが、現状で問題なさそうなので、コミットをスカッシュ&フォースプッシュしました。
2度目のフォースプッシュはコミットメッセージを修正するためです。
（Squash and Merge でも良かったかもしれません。）

レビューお願いいたします！

2024-09-25 04:22 UTC, YusukeHirao approved these changes

2024-09-25 04:22 UTC, merged